- name: add host to group 'just_created' with variable foo=42
  add_host:
    name: "{{ item }}"
    groups: webinstances
    web_admin: mohan@y2ytech.com
    ansible_become: yes
    ansible_connection: ssh
  loop: "{{ webinstance_output | json_query('results[*].tagged_instances[0].dns_name') }}"